### ISSUE TITLE
Tile not found after installation

### ISSUE THREAD

**Issue by feiglegithub** [googlecodelabs/wear-tiles#7]
When I install the start APP to the watch, it is not found in the add tiles list

**Comment by ataulm** [comment]
Thanks for the report @feiglegithub . Can you share a video repro so I can try to add the tile in the same way you are?

From a clean install of the `start` module's app artefact (Run app from Android Studio), I'm able to see the Goals tile in the "add tiles" list (I'm using Android Studio Dolphin and a Wear OS API 30 emulator):

<img width="253" alt="image" src="https://user-images.githubusercontent.com/2678555/184384708-d99530a1-4943-47c5-855c-d31a1ce7ed9f.png">

This codelab is currently being iterated on but it would still be helpful to understand so that we can make sure this isn't an issue in the new version.

**Comment by Cuberice** [comment]
For me, I had to change this in the start directories AndroidManifest.xml

![image](https://user-images.githubusercontent.com/6824471/195434408-21e4803c-49c0-4b11-a4e9-2d98e4d522d0.png)

**Comment by ataulm** [comment]
Hi Cuberice,

The codelab advises creating a new entry for the HelloWorldTileService in [the "Create a basic tile" step](https://developer.android.com/codelabs/wear-tiles#2) because the `MessagingTileService` entry will be necessary in step 5 onwards.

@feiglegithub I will close this issue for now but feel free to re-open if you're able to share repro steps.
